version: '3'
services:
  user-service:
    build: ./auth_service
    ports:
      - "8081:8081"
    container_name: auth_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
  user_profile:
    build: ./user_profile_service
    ports:
      - "8082:8082"
    container_name: user_profile_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
  chat-service:
    build: ./chat_service
    ports:
      - "8083:8083"
    container_name: chat_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "15672:15672" # Порт для управления RabbitMQ
#      - "5672:5672"
#  postgres:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#  mongodb:
#    image: mongo
#    ports:
#      - "27017:27017"
#  cassandra:
#    image: cassandra
#    ports:
#      - "9042:9042"
