# mkdir -p api/auth

# protoc -I api/auth --go_out=./pkg/api/auth/ --go_opt=paths=source_relative --go-grpc_out=./pkg/api/auth/ --go-grpc_opt=paths=source_relative api/auth/service.proto api/auth/messages.proto
