# mkdir -p app/auth

# protoc -I app/auth --go_out=./pkg/app/auth/ --go_opt=paths=source_relative --go-grpc_out=./pkg/app/auth/ --go-grpc_opt=paths=source_relative app/auth/service.proto app/auth/messages.proto
